__package_name__ = "AuriClass"
__authors__ = "Boas van der Putten"
__email__ = "ids-bioinformatics@rivm.nl"
__license__ = "AGPLv3"
__version__ = "0.2.0"
__description__ = "AuriClass predicts Candida auris clade from Illumina WGS data"
