name: Test

on: [push, pull_request]

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        cache-downloads: true
        environment-file: env.yaml

    - name: Conda list
      shell: bash -l {0}
      run: conda list

    - name: Run tests
      shell: bash -l {0}
      run: pytest
  cli_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          environment-file: env.yaml

      - name: Conda list
        shell: bash -l {0}
        run: conda list

      - name: Run tests
        shell: bash -l {0}
        run: |          
          set -ex

          check_exit_code () { exit_code=$?; echo "exit code: $exit_code"; if [ $exit_code -ne 0 ]; then exit 1; fi; }

          echo "Running help without error"
          python auriclass.py --help 1>/dev/null
          check_exit_code

          echo "Running version without error"
          python auriclass.py --version 1>/dev/null
          check_exit_code

          echo "Run fastq example without error"
          python auriclass.py --expected_genome_size 40000 60000 \
          --output report.tsv \
          -r tests/data/ref_sketch.msh \
          -c tests/data/clade_config.csv \
          tests/data/NC_001416.1_1.fq.gz tests/data/NC_001416.1_2.fq.gz
          check_exit_code

          cmp report.tsv tests/data/reference_report_fastq.tsv
          check_exit_code

          echo "Run fasta example without error"
          python auriclass.py --expected_genome_size 40000 60000 \
          --output report.tsv \
          -r tests/data/ref_sketch.msh \
          -c tests/data/clade_config.csv \
          tests/data/NC_001416.1.fasta.gz
          check_exit_code

          cmp report.tsv tests/data/reference_report_fasta.tsv
          check_exit_code

          echo "Running without read files and !:"
          ! python auriclass.py 
          check_exit_code

          echo "Running with invalid argument values and !:"
          ! python auriclass.py --expected_genome_size -1 1000000 tests/data/NC_001416.1_1.fq.gz tests/data/NC_001416.1_2.fq.gz
          check_exit_code

          echo "Running with non-existent argument and !:"
          ! python auriclass.py --does_not_exist tests/data/NC_001416.1_1.fq.gz tests/data/NC_001416.1_2.fq.gz
          check_exit_code

          echo "Running with non-existent file and !:"
          ! python auriclass.py tests/data/NC_001416.1_1.fq.gz tests/data/NC_001416.1_2.fq.gz tests/data/does_not_exist.fq.gz
          check_exit_code

          echo "Running with non-fastq, non-fasta file and !:"
          ! python auriclass.py tests/data/report.tsv
          check_exit_code
